### ISSUE TITLE
algoliaanalytics-node is not found in the npm registry -- Error 

### ISSUE THREAD

**Issue by JohnwesleyD** [algolia/algoliasearch-client-node#21]
I am trying to use the algolia seach capability in my meteor app and was able to add the meteor-search package from atmosphere (acemtp:algolia). All is well when i run the project locally. 

The issue occurs when i try to deploy the app on Modulus. It has a dependency on the algoliaanalytics-node and wants the author to publish to npm registry. 

Do you have any work around as in can i install the algolia-search locally and deploy them without the algoliaanalytics-node dependency...

Any help with this is greatly appreciated. :)

**Comment by redox** [comment]
Oh, that's weird; the "algoliaanalytics-node" should not be a dependency of the search package. It's actually a simple REST wrapper on top of our Analytics API implemented in a subdirectory of the search API Client: https://github.com/algolia/algoliasearch-client-node/tree/master/analytics

My meteor skills are pretty limited but is there any chance that `Npm.require` parses the `package.json` of this subdirectory? (https://github.com/algolia/algoliasearch-client-node/blob/master/analytics/package.json). Do you or @acemtp confirm?

Anyway, I think we'll either remove this nested `package.json` or move it to a dedicated project; what do you think @Nagriar ?

**Comment by Nagriar** [comment]
@JohnwesleyD I removed the analytics API from this repo, let me know if it solves the issue.

**Comment by vvo** [comment]
Closing, was solved by removing the dep
