### ISSUE TITLE
Request return whereas task is not finished

### ISSUE THREAD

**Issue by Masadow** [algolia/algoliasearch-client-node#22]
Hey there, I'm not sure this is a bug, I'm using latest 1.7.5.

When I try to call saveObject, the request return whereas the data is not saved yet into algolia. This means if I refresh my data, it still shows the old value whereas I received a confirm, I have to wait for about 5 seconds before the new value shows up.

**Comment by vvo** [comment]
> Hey there, I'm not sure this is a bug, I'm using latest 1.7.5.

Hi @Masadow!

You are right, this is not a bug, this is how Algolia works when writing objects to your index.

When adding objects to your index, the request returns as soon as the Algolia servers understood it. It is not guaranteed that if you do a search query right after your write query, you'll get a result.

If you want to know when a particular write task is finished, you can [use the taskID](https://github.com/algolia/algoliasearch-client-node#wait-indexing) every write request gives you:

```js
index.addObject({'firstname': 'Jimmie', 
                 'lastname': 'Barninger'}, function(error, content) {
  index.waitTask(content.taskID, function() {
    console.log("object " + content.objectID + " indexed");
  });
});
```

If you are building a search experience this should not be a big issue but let me know if you have a usecase that requires waiting for indexing operations.

**Comment by Masadow** [comment]
This is issue has no concerns with search experience.

The only concern is that my app backend is not as clear as it should since it is saying that the user request is done whereas it isn't.

However, your sample seems enough for my case since I just have to notify the user that the request is done inside the waitTask. Thanks

**Comment by nitinmagdumvista** [comment]
I didnt find a example Could you please help
I want to save objects and check if all are updated.

index.saveObjects(...).wait().then(response => {
  console.log(response);
});

i am using this API from https://www.algolia.com/doc/api-reference/api-methods/wait-task/?client=javascript 
above doc is very confusing - at the bottom its mentioned parameters but where we are passing those
we can use .wait which returns 

{
    "taskIDs": [
        114823164003,
        114823164004
    ],
    "objectIDs": [
        "6305c71cc81eb8aef2527984",
        "6305c7ebc81eb8aef2527998"
    ]
}

but how to verify its completed successfully

@vvo
