### ISSUE TITLE
API to get object ids from task id

### ISSUE THREAD

**Issue by nitinmagdumvista** [algolia/algoliasearch-client-node#29]
I am using this API to get the status of my task but in case if some tasks are completed means status is not completed then i want to update those objects present in that task ids

currently what i observed for around 1700 objects its created 2 task ids, and for 16K objects its creating 17 task ids
so if some of the tasks are not completed successfully i want to get objects from those tasks and update again

**Comment by nitinmagdumvista** [comment]
or not sure if there is better way to achieve this, could you please assist here

**Comment by nitinmagdumvista** [comment]
or instead of getting objects and updating them again is there a way to just retry using task id

**Comment by nitinmagdumvista** [comment]
@vvo

**Comment by vvo** [comment]
Hey there, I am no more working at Algolia, you'll have to wait here for an answer.
